# development:
#   cloud_name: college_key_foundation
#   api_key: ''
#   api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
#   enhance_image_tag: true
#   static_file_support: false

# production:
#   cloud_name: college_key_foundation
#   api_key: ''
#   api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
#   enhance_image_tag: true
#   static_file_support: true

# test:
#   cloud_name: college_key_foundation
#   api_key: ''
#   api_secret: <%= ENV['CLOUDINARY_API_SECRET'] %>
#   enhance_image_tag: true
#   static_file_support: false