# segment_write_key: 'axuyhKGkCoI1WgqAgZwynkpjQJGryPB7'
COLLEGE_ARCH_DATABASE_PASSWORD: 'college_arch'
SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: 'true'
SKIP_NODE_SASS_TESTS: 'true'
GMAIL_USERNAME: 'sparklessammy@gmail.com'
GMAIL_PASSWORD: 'IamSammy100%'