# segment_write_key: 'axuyhKGkCoI1WgqAgZwynkpjQJGryPB7'
COLLEGE_ARCH_DATABASE_PASSWORD: 'collegearchpassword'
SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: 'true'
SKIP_NODE_SASS_TESTS: 'true'
GMAIL_USERNAME: 'donotreply.collegearch@gmail.com'
GMAIL_PASSWORD: 'OkHurdScrappyD00!'
GOOGLE_OAUTH2_CLIENT_ID: '967307246653-bq26rr4gug57ds33s2f4de62dfabh3gu.apps.googleusercontent.com'
GOOGLE_OAUTH2_CLIENT_SECRET: '60KMCeG-yuEcfzr1HakGeL7X'
SECRET_KEY_BASE: "b431385b4f95ed75c3183bc77a2f3304a9d07d8317489396a2762ac761ee61c2298ead559872039d6228bab58dca137614d794b826dc3036c97684ac8328766c"